#' ---
#' title: ukb25465_ukb25468 combined - extraction of phenotypes and covariates
#' author: amacar
#' date: "Edited from ukb9246_extractPhenotypes_imagingSubset.R; . Modified: `r Sys.time()`"
#' output:
#'   html_document:
#'     toc: true
#'     toc_depth: 2
#'     theme: "flatly"
#'     highlight: "textmate"
#'     pdf_document:
#'     keep_tex: true
#' ---

library(pander)
library(ggplot2)
library(car)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
library(knitr)
library("GGally")

opts_chunk$set(include=TRUE, warnings=FALSE, echo=FALSE, results = "asis", tidy=TRUE, width=50, fig.width=8, fig.height=6)

panderOptions('knitr.auto.asis',FALSE)
# opts_chunk$set(dev="pdf", 
#                dev.args=list(type="cairo"),
#                dpi=96)
set.seed(50)

release="ukb25465_ukb25468"
# Define directories, dependent on  system
if (Sys.info()['sysname']=='Windows') {dir="P://workspaces/"} else {dir="/data/workspaces/lag/workspaces/"}
primary_dir=paste(dir,"lg-ukbiobank/primary_data",sep="")
working_dir=paste(dir,"lg-ukbiobank/working_data/amaia",sep="")
out_dir=paste(working_dir,"/pheno_files/genetic_v2/",release,"/",sep="")
out_plots_dir=paste(working_dir,"/pheno_files/genetic_v2/",release,"/plots/",sep="")
# Set working directory
opts_knit$set(root.dir = working_dir)
# create ouput directories if they don't already exist
dir.create(file.path(out_dir), showWarnings = FALSE)
dir.create(file.path(out_plots_dir), showWarnings = FALSE)


# get functions to calculate AIs
source(paste(working_dir,"/../../analysis/amaia/phenotypes/AIfunctions.R",sep=""))
source(paste(working_dir,"/../../analysis/amaia/phenotypes/relatedness_functions.R",sep=""))
# Start
setwd(working_dir)
rdata<-paste(out_dir,release,"_extractPhenotypes_imaging_extracted_PhenoCovs.RData",sep="")
#' if RData file exists, load, otherwise run everything
if (file.exists(rdata)) {
  load(rdata) } else {
  #' Read files generated by: ukb25465_ukb25468_selectCols_subsetSamples.R  
  #' Load data, for subset of dataset containing all imaging data.  
  input_file=paste(working_dir,"/demographic/",release,"_sqc_fam_selectedPhenotypes_imagingSamples.csv",sep="")
  data<-read.csv(input_file,header=TRUE,stringsAsFactors = FALSE) #nrows=3
  data<-subset(data,imaging_T1==1)
  colnames_old<-colnames(data)
  # clean colnames to match fields...
  colnames(data)<-gsub("_.left.","_left",gsub("_.right.","_right",colnames(data)))
  colnames(data)<-gsub("_\\.|\\+|\\.","_",colnames(data))
  colnames(data)<-gsub("^f_","f.",colnames(data))
  colnames(data)<-gsub("_$","",gsub("__","_",colnames(data)))

  # info about variables, colnames etc
  data_cols<-read.csv(gsub("imagingSamples|allSamples","variables",input_file),header=TRUE,stringsAsFactors = FALSE) #nrows=3
  #' QC information
  sqc_info<-read.csv(paste(primary_dir,"/genetic_data/release_May2017/data/sqc_info.csv",sep=""),sep=",",quote = "\"",header=FALSE)

  #' Flag samples to keep after QC (genetic_data)
  #' QC-ed samples, from genetic analysis:
  sampleQC<-read.table("/data/workspaces/lag/workspaces/lg-ukbiobank/working_data/genetic_data/sample_QC/ukb9246_BritishUKB.samples2keep")
  sampleQC$sample2keep<-1
  data<-merge(data,sampleQC[,c(-2)],by.x="f.eid",by.y="V1",all.x=TRUE)
  data$sample2keep[is.na(data$sample2keep)]<-0
  #' White British ancestry
  pander(table(data$in_white_British_ancestry_subset)) 
  # 18426 white British ancestry
  #' Genetic QC
  pander(table(data$sample2keep)) # 18377 sample2keep, white british + genetic sample QC
  pander(table(sample2keep=data$sample2keep,whiteBritish=data$in_white_British_ancestry_subset)) 
  #' There are 30 whiteBritish that are not kept due to QC

  #' Check relatedness. Relationship pairs, if Kinship coeff > 0.0442
  rel_pairs<-read.table(paste(primary_dir,"/genetic_data/release_May2017/data/ukb1606_rel_s488366.dat",sep=""),stringsAsFactors = FALSE,header=TRUE)
  # subset relationship matrix to samples within imaging subset only
  # include only pairs if both are within the imaging set/ after QC
  w1<-which(rel_pairs$ID1 %in% data$f.eid[data$sample2keep==1])
  w2<-which(rel_pairs$ID2 %in% data$f.eid[data$sample2keep==1])
  w<-intersect(w1,w2) # 323 after sample2keep==1
  rel_pairs_imaging<-rel_pairs[w,]
  table((rel_pairs_imaging$ID1 %in% data$f.eid) & (rel_pairs_imaging$ID2 %in% data$f.eid) )
  samples2check<-unique(c(rel_pairs_imaging$ID1,rel_pairs_imaging$ID2))
  rm(w1,w2,w)
  #' Kinship coefficient within imaging subset
  hist(rel_pairs_imaging$Kinship,breaks=100)
  summary(rel_pairs_imaging$Kinship)
  table(rel_pairs_imaging$Kinship> 0.0625) # 230 third degree relatives
  # create new variable to flag samples with some related sample
  data$sampleRel<-0
  data$sampleRel[which(data$f.eid %in% samples2check)]<-1
  pander(table(data$sample2keep,data$sampleRel)) # 18377, of which 629 have a relatedness flag
  ## check types of relatedness
  #' pairs of MZ twins:
  subset(rel_pairs_imaging,Kinship>0.4)
  subset(data,f.eid=="3429006"|f.eid=="3047939")[,c("f.eid","imaging","imaging_T1","sample2keep","sampleRel")]
  #' pairs of 1st degree relatives
  dim(subset(rel_pairs_imaging,Kinship>0.15&Kinship<0.4)) # 141 pairs of 1st degree relatives
  #' pairs of 2nd degree relatives
  dim(subset(rel_pairs_imaging,Kinship>0.06&Kinship<0.15)) # 106 pairs of 1st degree relatives
  
  
  if (!file.exists(paste(release,"sampleQC_v2_imaging_not_related.samples",sep="_"))){
    #' Need to remove: 1 relative per pair
    # data contains 14520 samples with imaging measures, subset to sample2keep
    data<-related_clean(sdata=subset(data,sample2keep==1),rel_info=rel_pairs_imaging)
    # 18377 clean QCed samples
    #' Number of samples to remove due to relatedness
    table(data$RelRemove1)
    samples2exclude<-subset(data,RelRemove1==1)[,c("f.eid","f.eid")]# 165 samples to exclude due to relatedness
    # save file, for reference:
    write.table(samples2exclude,file=paste(release,"related_imaging_exclude.samples",sep="_"),sep="\t",quote=FALSE,col.names = FALSE,row.names = FALSE)
    #' Save list of samples belonging to the "white British ancestry subset"
    samples2keep<-subset(data,sample2keep==1&is.na(RelRemove1))[,c("f.eid","f.eid")] # 18057
    write.table(samples2keep,file=paste(release,"sampleQC_v2_imaging_not_related.samples",sep="_"),sep="\t",quote=FALSE,col.names = FALSE,row.names = FALSE)
    # subset data to exclude related individuals:
    data<-subset(data,is.na(RelRemove1))
    } else {
    samples2keep<-read.table(paste(release,"sampleQC_v2_imaging_not_related.samples",sep="_"))[,1]
    samples2keep<-data.frame(samples2keep); colnames(samples2keep)<-c("f.eid")
    samples2keep$samples2keep<-1
    data<-merge(data,samples2keep,all.x=TRUE)
    data$sample2exclude<-0
    data$sample2exclude[which(is.na(data$sample2keep))]<-1
    data<-subset(data,sample2keep==1)
    rm(samples2keep)
  }
  
  # read field names/definitions
  field_files<-paste("field_definitions/",list.files("field_definitions/"),sep="")
  fields<-data.frame(Field.ID=character(),Description=character(),newname=character())
  for (f in field_files) {
    tmp<-read.csv(f,header=TRUE,stringsAsFactors = FALSE)
    tmp$newname<-gsub("-|,| ","_",gsub("\\(|\\)|,|\\'","",gsub(" ","_",tmp$Description)))
    fields<-rbind(fields,tmp[,colnames(fields)]); rm(tmp)
  }; rm(f)
  fields$newname<-gsub("_$","",gsub("/","_",gsub("__","_",gsub("_\\.|\\+|\\.","_",fields$newname))))
  fields$newname<-gsub("__","_",gsub("grey_white_matter","grey_white",fields$newname))

  # define colID and colname
  fields$colID<-NA
  fields$colname<-NA
  # if colnames in data are names after field ID
  w<-unlist(sapply(paste("f.",fields$Field.ID,"_",sep=""),function(x) grep(x,colnames(data))))
  w1<-match(gsub("f.|\\.|_","",names(w)),fields$Field.ID)
  w<-w[!is.na(w1)]
  w1<-w1[!is.na(w1)]
  w2<-unlist(sapply(paste("f.",fields$Field.ID,".",sep=""),function(x) colnames(data)[grep(x,colnames(data))]))
  w2<-w2[w1]
  # add
  fields$colID[w1]<-w
  fields$colname[w1]<-w2
  rm(w,w1,w2)
  # if colnames in data are named after newname
  w3<-which(fields$newname %in% colnames(data))
  w3<-w3[!is.na(w3)]
  w4<-match(fields$newname[w3],colnames(data))
  fields$colID[w3]<-w4
  fields$colname[w3]<-fields$newname[w3]
  rm(w3,w4)
  # how many fields are there?
  table(is.na(fields$colID))
  fields$colname<-colnames(data)[fields$colID]
  # generate new column with newname (with descriptive content)
  data[,fields$newname[!is.na(fields$colname)]]<-data[,fields$colname[!is.na(fields$colname)]]

  # keep all columns just in case!?
  # extract info about variables from description
  fields$hemisphere<-NA
  fields$hemisphere[grep("left",tolower(fields$Description))]<-"left"
  fields$hemisphere[grep("right",tolower(fields$Description))]<-"right"
  fields$type<-NA
  keytypes<- c("volume "," fa "," icvf "," isovf "," md ", " mo ", " od ",paste(" l",1:5," ",sep=""),"hand grip")
  for (key in keytypes) {
    fields$type[grep(key,tolower(fields$Description))]<-gsub(" ","",toupper(key))
  }
  
  table(fields$type)
  table(fields$hemisphere,fields$type)
  table(is.na(fields$hemisphere),fields$type)
  
  #' for T1 measures: 72 volumes per hemisphere, 20 volumes that are not hemispheric
  #' for DTI measures: 33 measures/type that are symmetric, and 9 that are not
  #' ## of which, some are FA skeleton and others are tracts
  
  # extract region, as well as I can
  fields$region<-gsub("_\\(right\\)|_\\(left\\)|_left|_right","",
                      gsub("grey_matter_in_","",gsub("Volume_of_","",
                      gsub(paste("Mean_",c("FA","ICVF","ISOVF","MD", "MO", "OD",paste("L",1:5,sep="")),"_in_",sep="",collapse="|"),"",
                      gsub(paste("Weighted_mean_",c("FA","ICVF","ISOVF","MD", "MO", "OD",paste("L",1:5,sep="")),"_in_",sep="",collapse="|"),"",
                                                     fields$newname
                                                     )))))
  fields$region<-gsub("-|,| ","_",gsub("\\(|\\)|,|\\'","",fields$region))
  # subcortical volumes have two measures each: grey volume and white+grey volume
  # but this is not reflected in the name (just lower vs upper case), so append to white+grey
  w_vol<-grep("Volume of",fields$Description)
  w_Ngrey<-grep("grey|white|fluid|brain",fields$Description,invert=TRUE)
  fields$region[intersect(w_vol,w_Ngrey)]<-paste(fields$region[intersect(w_vol,w_Ngrey)],"_greywhite",sep="")
  rm(w_vol,w_Ngrey)
  #
  colnames(data)<-gsub("-|,| ","_",gsub("\\(|\\)|,|\\'","",colnames(data)))
  
  #------------------------------
  #' Calculate total L and R grey matter volume
  #------------------------------
  #' Define new variables: total of left and right volume of grey matter, and calculate AI:
  #----------------------------------------------------------
  vol_left<-fields$newname[grep("volume_of_grey_matter_in_*.*left",tolower(fields$newname))]
  vol_right<-fields$newname[grep("volume_of_grey_matter_in_*.*right",tolower(fields$newname))]
  # compute total left and right volume
  data$Volume_total_left<-apply(data[,vol_left],1,sum)
  data$Volume_total_right<-apply(data[,vol_right],1,sum)
  rm(vol_left,vol_right)
  # add total GM volume to fields
  tmp<-data.frame(matrix(nrow=2,ncol=8));colnames(tmp)<-colnames(fields)
  tmp[1,]<- c("-","Sum of all GM volumes (left)","Volume_total_left","","","left","VOLUME","Volume_total")
  tmp[2,]<- c("-","Sum of all GM volumes (right)","Volume_total_right","","","right","VOLUME","Volume_total")
  fields<-rbind(fields,tmp); rm(tmp)
  
  #------------------------------
  #' Asymmetry indices
  #------------------------------
  #' Calculate asymmetry indeces for all regions with left + right
  region_nH<-unique(subset(fields,!is.na(colID)&is.na(hemisphere))$region)
  regionH<-unique(subset(fields,!is.na(colID)&!is.na(hemisphere))$region)
  
  #' From Guadalupe et al. (2016)
  #' Asymmetry Indices (AI) were defined as the relative volume difference between the left and right structure in relation to its total bilateral volume: 
  #' (Left - Right)/(Left + Right). 
  #' To exclude possible outliers in volumes or AIs we used an adaptive SD threshold (SDThresh) depending on each dataset's sample size 
  #' * N < 150 ? SDThresh = 2.5
  #' * 150 = N = 1000 ? SDThresh = 3 
  #' * N > 1000 ? SDThresh = 3.5.
  
  #' I will use thr=4; since N> 8000
  
  #' Calculate AIs per region
  data2<-data # backup data
  thr=4
  for (x in regionH)  {
    t<-subset(fields,region==x)
    tmp<-lapply(unique(t$type), function(y){ calculateAIs(y=y,x=x,thr=thr)})
    tmp2<-do.call("cbind",tmp)
    data2<-cbind(data2,tmp2)
    rm(t,tmp,tmp2)
  } 
  #' Plot histograms of the AIs
  #' Note that outliers have not been included when computing the median, but are still present; will need to remove later.
  thr=4; t=4
  # For the three AI indexes, get number of outliers and generate histograms
  # , will be the same as the run with BioCovs, because lm has not been run yet but...
  for (ai in c("AI","AIfa","AIabs")) { # c("AIfa","AIabs")){
    # define columns of interest
    cols_ai<-colnames(data2)[grep(paste(ai,"_",sep=""),colnames(data2))]
    # calculate
    out<-lapply(cols_ai,function(x){ histo_out_AIs(x,data2=data2,thr=thr) })
    # reorganize
    out_df<-data.frame(n_outliers=as.numeric(unlist(sapply(out,"[[",1))))
    out_df$name<-cols_ai
    # get histograms
    hists<-sapply(out,"[[",2)
    names(hists)<-cols_ai
    # plot distribution of number of outliers
    ## to visually check the ones that have many outliers
    title<-paste("\nHistogram of number of outliers: ",ai,"\nOutliers = Mean +- ",thr,"SD",sep="")
    g<-ggplot(data=out_df,aes(x=n_outliers))+geom_histogram(binwidth=1) + theme_bw() + labs(title=title) 
    # save plots
    ggsave(g,file=paste(out_plots_dir,ai,"_outliers_per_phenotype.pdf",sep=""),width=10)
    # assign
    assign(paste("out_df_",ai,sep=""),out_df)
    assign(paste("outlier_distribution_",ai,sep=""),g)
    assign(paste("histograms",ai,sep=""),hists)
    # clean
    rm(cols_ai,out,out_df,hists,title,g)
  }
  rm(ai)
  
  #------------------
  # save AI_VOLUMES, only!
  tmp<-out_df_AI[grep("VOLUME",out_df_AI$name),]
  ai="AI_VOLUME"
  title<-paste("\nHistogram of number of outliers: ",ai,"\nOutliers = Mean +- ",thr,"SD",sep="")
  g<-ggplot(data=tmp,aes(x=n_outliers))+geom_histogram(binwidth=1) + theme_bw() + labs(title=title) 
  # save plots
  ggsave(g,file=paste(out_plots_dir,ai,"_outliers_per_phenotype.pdf",sep=""),width=5)
  rm(g,title,ai,tmp)
  #------------------
  
  #' Save all histograms, per AI definition
  for (ai in c("AI")){ # "AIabs",,"AIfa"
    hists<-get(paste("histograms",ai,sep=""))
    pdf(paste(out_plots_dir,ai,"_histograms_all_phenotypes.pdf",sep=""),onefile = TRUE)
    # for (h in ls(pattern=paste("histogram_",ai,sep=""))){
    for (h in 1:length(hists)){
      grid.arrange(hists[[h]])
    }
    dev.off()
  }
  rm(hists)
  
  # get data back
  data<-data2; rm(data2) # 
  #------------------------------
  
  #------------------------------
  #' Define columns containing imaging variables of interest
  # volume_cols<-colnames(data)[grep(paste(c(regionH,region_nH),collapse="|"),colnames(data))]
  volume_cols<-colnames(data)[grep("volume",tolower(colnames(data)))]
  dti_cols<-colnames(data)[grep("fa_skeleton",tolower(colnames(data)))]
  dti_tract_cols<-colnames(data)[grep("tract",tolower(colnames(data)))] # tracts should not have FA, otherwise duplicated phenos!
  dti_tract_cols<-dti_tract_cols[grep("fa_skeleton",tolower(dti_tract_cols),invert=TRUE)]
  handgrip_cols<-colnames(data)[grep("hand_grip",tolower(colnames(data)))]
  #
  motion_cols<-colnames(data)[grep("motion",tolower(colnames(data)))]
  
  #' ## Define 'default covariates'  
  #' 
  #' PCs, available from release  
  # check visually
  # plot(data[,"PC1"],data[,"PC2"])
  # plot(data[data$in_white_British_ancestry_subset==1,"PC1"],data[data$in_white_British_ancestry_subset==1,"PC2"])
  pcs<-colnames(data)[grep("^PC",colnames(data))]
  # define first 40 PCs
  pcs<-pcs[1:40] # initially used 10 only, but get them all and then decide how many to include within the LM
  print("is.na PC1'")
  table(is.na(data[,pcs[2]])) 
  #' sample QC has been completed, so all contain PCs
  
  #' Age at assesment, instance 2 --> age at imaging visit
  age1<-colnames(data)[grep("^Age_when",colnames(data))] # this is average age across three visits
  age<-"f.21003_2_0" # age at imaging visit
  print("is.na age")
  table(is.na(data[,age1])) # no missing data
  table(is.na(data[,age])) # no missing data, this is new!
  # if we include this variable in the lm, will remove ~ 642 samples
  
  # calculate age from birth date and date attending assesment center (imaging visit): f.53.2.0
  # birth year:  f.34.0.0
  # birth month: f.52.0.0
  data$birth_y<-as.character(data$Year_of_birth)
  data$birth_m<-as.character(data$Month_of_birth)
  data$birth_m[nchar(data$Month_of_birth)==1]<-paste("0",data$Month_of_birth[nchar(data$Month_of_birth)==1],sep="")
  data$birth_ym<-as.Date(paste(data$birth_y,data$birth_m,"01",sep="-"),format="%Y-%m-%d")
  data$date_imaging_ym<-as.Date(data$f.53_2_0,format="%Y-%m-%d")
  data$date_imaging_y<-as.numeric(sapply(strsplit(as.character(data$f.53_2_0),"-"),"[[",1))
  # calculate at age imaging, taking into account year and month
  data$age_imaging<-round(as.numeric(data$date_imaging_ym-data$birth_ym)/365.25,digits=0)
  data$age_imaging1<-round(as.numeric(data$date_imaging_ym-data$birth_ym)/365.25,digits=1)
  data$age_imaging_f<-floor(as.numeric(data$date_imaging_ym-data$birth_ym)/365.25)
  data$age_imaging_y<-data$date_imaging_y-as.numeric(data$birth_y)
  plot(data$age_imaging,data[,age])
  plot(data$age_imaging_y,data[,age])
  plot(data$age_imaging_f,data[,age])
  plot(data$age_imaging_y,data$age_imaging)
  plot(data$age_imaging_y,data$age_imaging_f)
  plot(data$age_imaging_y,data$age_imaging1)
  # compare to reported age
  head(data[which(data$age_imaging-data[,age]!=0),c("f.eid",age,"f.53_2_0","birth_y","birth_m","date_imaging_ym","date_imaging_y","age_imaging","age_imaging_y","age_imaging_f","age_imaging1")])
  head(data[which(data$age_imaging_f!=data[,age]),c("f.eid",age,"f.53_2_0","birth_y","birth_m","date_imaging_ym","date_imaging_y","age_imaging","age_imaging_y","age_imaging_f","age_imaging1")])
  
  # go with age_imaging1, more precision...
  data$age<-data[,"age_imaging1"]
  age<-"age"
  # compute age2, as recommended: (age-meanAge)2
  meanAge<-mean(data[,age],na.rm = TRUE) # 63.32624
  data$zage2<-(data[,age]-meanAge)^2 # age2: (age-meanAge)^2
  rm(meanAge)
  
  #' Assesment center
  assesmentC<-colnames(data)[grep("UK_Biobank_assessment",colnames(data))] # missing, need to add!
  #' Sex  
  sex<-"sex"
  # boxplot(data[,age]~data[,sex]) # males are older than females on average
  print("is.na sex")
  pander(table(is.na(data[,sex])))
  #' Males and females
  pander(table(data[,sex]))
  #' Some missing data, same as people without Genetic info.  
  #' Select Genotyping array and batch.  
  array<-colnames(data)[grep("array",colnames(data))]
  batch<-colnames(data)[grep("^batch",colnames(data))]
  # total brain volume
  tBV<-"Volume_of_brain_grey_white" # "Volume_of_brain_grey_white_normalised_for_head_size"
  # scanner position parameters
  scanner_position<-colnames(data)[grep("brain_position",colnames(data))]
  scanner_position_pairs<-ggpairs(data[,scanner_position])
  # scanner_position_pairs_samples2keep<-ggpairs(subset(data,sample2keep==1)[,scanner_position])
  ggsave(scanner_position_pairs,file=paste(out_plots_dir,"scanner_position_pairs.pdf",sep=""),width=10,height=10)
  # ggsave(scanner_position_pairs_samples2keep,file=paste(out_plots_dir,"scanner_position_pairs_samples2keep.pdf",sep=""),width=10,height=10)
  rm(scanner_position_pairs) #scanner_position_pairs_samples2keep,
  
  #' Define binary and quantitative covariates
  bin_covs<-c(sex,assesmentC,array,batch)
  quant_covs<-c(age,"zage2",pcs,scanner_position,tBV)
  # plot pairs for all quant covariates
  quant_covs_pairs_samples2keep<-ggpairs(subset(data,sample2keep==1)[,quant_covs])
  ggsave(quant_covs_pairs_samples2keep,file=paste(out_plots_dir,"quant_covs_pairs_samples2keep.pdf",sep=""),width=10,height=10)
  rm(quant_covs_pairs_samples2keep)
  
  #' Visually inspect covariates to see whether there are outliers # if so, should blank?!
  quant_covs_hist_out<-lapply(quant_covs,function(x){histo_out_AIs(data2=subset(data,sample2keep==1),x,thr=6)})
  # save plot
  hists<-sapply(quant_covs_hist_out,"[[",2)
  pdf(paste(out_plots_dir,"quant_covariates_outliers.pdf",sep=""),onefile = TRUE)
  for (h in 1:length(hists)){ grid.arrange(hists[[h]]) }
  dev.off()
  rm(hists)
  #' there are two very clear outliers in scanner_position_x; blank them # more??? **
  w<-which(data[,scanner_position[1]]<(-20))
  if (length(w)>0) {data[w,scanner_position[1]]<-NA}
  rm(w)
  
  #' ## Define (not imaging) phenotypes:  
  height<-"f.50_0_0" # standing height
  # weight<-"f.3160_0_0" # skip
  birthweight<-"f.20022_0_0"
  bmi<-"f.21001_0_0"
  handedness<-colnames(data)[grep("^handed|^f.1707.",tolower(colnames(data)))]
  handedness<-"f.1707_0_0" # handedness at initial assesment
  # define congruent handedness, right or left only
  data$Lhandedness<-NA
  data$Lhandedness[data[,handedness]==1]<-0
  data$Lhandedness[data[,handedness]==2]<-1 # left-handers as cases
  pander(table(data$Lhandedness))
  
  #' Define phenotypes of interest
  phenos<-c(height,bmi,"Lhandedness",birthweight,volume_cols,dti_cols,dti_tract_cols,motion_cols,handgrip_cols) # add unique to avoid having duplicated columns!
  # select phenotypes and samples2keep
  data_s<-subset(data,sample2keep==1)[,c("f.eid","f.eid",bin_covs,quant_covs,phenos)]
  # 18057 samples-> imaging T1 
  
  # new colnames
  # phenos2<-c("height","weight","BMI","handedness")
  phenos2<-c("height","bmi","handedness","birthweight",volume_cols,dti_cols,dti_tract_cols,motion_cols,handgrip_cols) # add unique to avoid having duplicated columns!
  bin_covs2<-c("sex","assessment_centre","array","batch")
  quant_covs2<-c("age","zage2",paste("PC",1:40,sep=""),scanner_position,"totalBV")
  colnames(data_s)<-c("ID1","ID2",bin_covs2,quant_covs2,phenos2)
  
  #' Convert binary covariates into factors
  data_s[,bin_covs2]<-apply(data_s[,bin_covs2],2,function(x) as.factor(x))
  data_s<-subset(data_s,!is.na(data_s$sex))
  # pander(str(data_s[,phenos2]))
  data_s$handedness<-factor(data_s$handedness,levels=c(0,1))
  
  #' Save raw phenotypes with covariates + list of phenotypes
  #' note: these raw phenotypes have NOT been cleaned for outliers
  write.table(data_s,paste(out_dir,release,"_imaging_covsImagingPhenotypes_wHeader.table",sep=""),sep="\t",quote=FALSE,row.names = FALSE,col.names=TRUE)
  write.table(phenos2,paste(out_dir,release,"_imaging_generalPhens_IDP_residuals_phenotypes.list",sep=""),col.names = FALSE,row.names = FALSE,quote=FALSE)
  rm(data_s)

  }

rm(data,data_cols,field_files,fields)
rm(out_df_AI, out_df_AIabs, out_df_AIfa)
rm(rel_pairs,rel_pairs_imaging)
rm(sampleQC,samples2exclude,samples2keep, sqc_info)
rm(handedness,h,handgrip_cols,height)
rm(histogramsAI,histogramsAIabs,histogramsAIfa)
rm(input_file,key,keytypes)
rm(motion_cols)
rm(outlier_distribution_AI, outlier_distribution_AIabs, outlier_distribution_AIfa)
# save image
save.image(paste(out_dir,release,"_extractPhenotypes_imaging_extracted_PhenoCovs.RData",sep=""))
