library(gridExtra);library(grid);library(ggplot2);library(cowplot)
library(GGally)
library(xtable)
library(tidyr)
library(plyr);library(dplyr)

options(stringsAsFactors = FALSE)
# GCTA power calculator - for genetic correlation
## between a behavioural trait/ brain asymmetry

if (Sys.info()['sysname']=='Windows') {dir="P://workspaces/"} else {dir="/data/workspaces/lag/workspaces/"}
working_dir=paste(dir,"lg-ukbiobank/analysis/amaia/genetic_analysis/release_v2/",sep="")
sum_dir=paste(dir,"lg-multilateral/working/Data/GWAS_sumstats/",sep="")

subset_name="imagingT1_N18057"
out_dir=paste(dir,"lg-ukbiobank/working_data/amaia/genetic_data/release_v2/cal/h2/",subset_name,"/output/PT/power/",sep="")
dir.create(file.path(out_dir), showWarnings = FALSE)

setwd(working_dir)

# load RData if it exists
# load(paste(out_dir,"GCTA_PowerCalculator_gencor_VOLUMES_MinMax_GWASpublic.RData",sep=""))

# Get functions from
source("GCTA_PowerCalculator.R")
source("../h2.obs2liab.R")

# colors
colrs=c("#d95f02","#1f78b4","#33a02c","#000000")  #'#1b9e77','#d95f02',"#1f78b4","#a6cee3",
greens<-c('#f7fcfd','#e5f5f9','#ccece6','#99d8c9','#66c2a4','#41ae76','#238b45','#006d2c','#00441b')[-c(1:3)]
blues<-c('#fff7fb','#ece7f2','#d0d1e6','#a6bddb','#74a9cf','#3690c0','#0570b0','#045a8d','#023858')[-c(1:3)]


# read estimates from heritability analyses, min and max for phenotypes of interest
## generated by: GCTA_LDSC_LDAK_output_PT_N18057.R

##

estimates<-read.csv(paste(dir,"/lg-ukbiobank/working_data/amaia/genetic_data/PT/imagingT1_N18057/","estimates4power.csv",sep=""),header=TRUE)
estimates<-subset(estimates,adj=="")
# estimates<-estimates[,c("X","Min.","Max.")]
# colnames(estimates)<-c("Program","Min","Max")
# estimates$Min<-round(estimates$Min,digits=2)
# estimates$Max<-round(estimates$Max,digits=2)
estimates$N1<-18057

#----------------------------------
# read table that summarizes possible GWAS results - QTs
#----------------------------------
sum<-read.csv(paste(sum_dir,"PublicSummary_stats_overview_h2.csv",sep=""),stringsAsFactors = FALSE)
sum$type<-NA
sum$type[sum$Trait=="Quant"]<-"QT"
sum$type[sum$Trait=="Binary"]<-"CC"
table(sum$type)
sum$Author1<-sapply(strsplit(sum$First.Author," "),"[[",1)
sum$Ref<-paste(sum$Author1,sum$Year,sep="")

# the h2 estimates are from ldsc/sumher, in observed scale. Transform to liability scale. Per h2 run: ldsc, sumher-ldak and sumher-gcta
# ldsc
sum$h2l_ldsc<-apply(sum,1,function(x) {
  if (x["type"]=="CC") {
    h2l<-h2liab(prevalence=as.numeric(x["PopPrevalence"]),cases = as.numeric(x["Ncases"]),controls=as.numeric(x["Ncontrols"]),h2obs = as.numeric(x["h2_ldsc"]))
    
  } else { 
    h2l<-x["h2_ldsc"] }
  h2l<-round(as.numeric(h2l),digits=2)
  return(h2l)
} )
# sumher-gcta
sum$h2l_sumher_gcta<-apply(sum,1,function(x) {
  if (x["type"]=="CC") {
    h2l<-h2liab(prevalence=as.numeric(x["PopPrevalence"]),cases = as.numeric(x["Ncases"]),controls=as.numeric(x["Ncontrols"]),h2obs = as.numeric(x["h2_sumher_gcta"]))
    
  } else { 
    h2l<-x["h2_sumher_gcta"] }
  h2l<-round(as.numeric(h2l),digits=2)
  return(h2l)
} )
# sumher-ldak
sum$h2l_sumher_ldak<-apply(sum,1,function(x) {
  if (x["type"]=="CC") {
    h2l<-h2liab(prevalence=as.numeric(x["PopPrevalence"]),cases = as.numeric(x["Ncases"]),controls=as.numeric(x["Ncontrols"]),h2obs = as.numeric(x["h2_sumher_ldak"]))
    
  } else { 
    h2l<-x["h2_sumher_ldak"] }
  h2l<-round(as.numeric(h2l),digits=2)
  return(h2l)
} )

sum$h2lSE_ldsc<-paste(sum$h2l_ldsc," (",sum$se_ldsc,")",sep="")
sum$h2lSE_sumher_gcta<-paste(sum$h2l_sumher_gcta," (",sum$se_sumher_gcta,")",sep="")
sum$h2lSE_sumher_ldak<-paste(sum$h2l_sumher_ldak," (",sum$se_sumher_ldak,")",sep="")

cols<-c("PMID","Ref","Reported.trait","N","Ncases","Ncontrols","PopPrevalence","h2lSE_ldsc","h2lSE_sumher_gcta","h2lSE_sumher_ldak")
# sum[is.na(sum)]<-""
print(xtable(sum[,cols],caption="Summary of literature."),include.rownames=FALSE) 

# select cols that will exclude
w<-grep("Rietveld|Sniekers|Okbay|Adams|Hou|Wray|Sklar",sum$First.Author)
sum<-sum[-w,]; rm(w)
rownames(sum)<-1:NROW(sum)
sink(paste(sum_dir,"PublicSummary_stats_overview_h2.tex",sep=""))
print(xtable(sum[,cols],caption="Summary of literature."),include.rownames=FALSE) 
sink()

write.csv(sum,paste(sum_dir,"PublicSummary_stats_overview_h2_liab.csv",sep=""),row.names=FALSE)

# plot
lowerfun <- function(data,mapping){
  ggplot(data = data, mapping = mapping) +
    geom_point() + geom_abline(intercept=0,slope=1) +
    scale_x_continuous(limits = c(0,0.5)) +
    scale_y_continuous(limits = c(0,0.5)) + theme_bw()
}  

ggpairs(sum[,c("h2l_ldsc","h2l_sumher_gcta","h2l_sumher_ldak")], lower = list(continuous = wrap(lowerfun)))
#----------------------------------

#----------------------------------
# Define variables, h2 and rg - for all models
rgs=unique(c(seq(0.01,0.30,0.001),seq(0.31,0.49,0.01),seq(0.5,1,0.05))) #60
#----------------------------------
# Model Trait 2 from summary table
#----------------------------------
resultsQT <- data.frame(trait=as.character(),N_1 = as.numeric(), N_2=as.numeric(), h2_1 = as.numeric(), h2_2= as.numeric(), rg= as.numeric(),h2_def=as.character(),
                      se = as.numeric(), ncp = as.numeric(), pwr = as.numeric())

resultsCC <- data.frame(trait=as.character(),N_1 = as.numeric(), N_2cases=as.numeric(), N_2controls=as.numeric(),case_prev=as.numeric(),h2_1 = as.numeric(), h2_2= as.numeric(), rg= as.numeric(),h2_def=as.character(),
                      se = as.numeric(), ncp = as.numeric(), pwr = as.numeric())

h2_trait1<-unique(c(estimates$h2))
n1<-unique(estimates$N1)

for (j in 1:NROW(estimates)){
  h1<-estimates$h2[j]
  p1<-estimates$program[j]
  
  if (p1=="GCTA"|p1=="LDSC") {
    h2_def="h2l_ldsc"
  } else if (p1=="SUMHER-ldak") {
    h2_def="h2l_sumher_ldak"
  } else if (p1=="SUMHER-gcta") {
        h2_def="h2l_sumher_gcta"
    }
  
  for (i in 1:NROW(sum)){
  
  h2<-sum[i,h2_def]
    if (!is.na(h2)){
      k<-as.numeric(sum$PopPrevalence[i])
      n2<-as.numeric(sum$N[i])
      n2_c<-as.numeric(sum$Ncases[i])
      n3_c<-as.numeric(sum$Ncontrols[i])
      t<-sum$Trait_name[i]
      for (rg in rgs){
        if (sum$type[i]=="QT") {
          tmp<- calcBiQt(n1=n1, n2=n2,hsq1 =h1,hsq2=h2,rg=rg,overlap=FALSE)
          resultsQT[nrow(resultsQT)+1,] <- c(list(trait=t,N_1=n1,N_2=n2,hsq1=h1,hsq2=h2,rg=rg,h2_def=h2_def),tmp)
        } else if (sum$type[i]=="CC"){
        # Function for bivariate analysis of a quantitative trait and a binary trait (case-control study)
          tmp<-calcBiQtCc(n=n1,ncase=n2_c,ncontrol=n3_c,hsq1 =h1,hsq2=h2,rg=rg,K=k)
          resultsCC[nrow(resultsCC)+1,] <- c(list(trait=t,N_1=n1,N_2cases=n2_c,N_2controls=n3_c,case_prev=k,
                                              hsq1=h1,hsq2=h2,rg=rg,h2_def=h2_def),tmp)
        } }
      }
    rm(k,n2,n2_c,n3_c,t)
  }
  rm(h2)
}

results<-merge(resultsCC,resultsQT,all=TRUE,stringsAsfactors=FALSE)
# merge with estimates, to get program
results<-merge(results,estimates,by.x=c("N_1","h2_1"),by.y=c("N1","h2"))
results$N_1<-as.factor(results$N_1)
results$N_2controls<-as.factor(results$N_2controls)
results$N_2cases<-as.factor(results$N_2cases)
# results$h2_1<-as.factor(results$h2_1)
results$h2_2_f<-as.factor(results$h2_2)
results$prev_f<-as.factor(results$case_prev)


#-----------------------
# save files
write.csv(resultsQT,paste(out_dir,"power_calc_results_AI_QT.csv",sep=""),row.names = FALSE)
write.csv(resultsCC,paste(out_dir,"power_calc_results_AI_CC.csv",sep=""),row.names = FALSE)

#-----------------------------------------------
# Make plots
#-----------------------------------------------

## calculate minimum rhog at alpha=0.05 and beta=0.80, for each facet/condition
results_pwr<-subset(results,pwr>=0.8)
min_rhog<-ddply(results_pwr,.(measure,trait,program),summarise,min_rg=min(rg,na.rm=TRUE))


## for the scenarios of interest, define variables

# trait 1: imaging phen, h2 min and max, fixed N
# trait 2: language or other phen, looping through values of h2
tapply(subset(results,pwr<0.99)$rg,subset(results,pwr<0.99)$measure,summary)
results2<-subset(results, (measure=="AI"&rg<=0.30) | (measure=="L"&rg<=0.20) | (measure=="R"&rg<=0.20) )
results2$trait<-gsub("EduYears","EA",results2$trait)
results2$trait<-gsub("IQ","Intelligence",results2$trait)
results2$trait<-as.factor(results2$trait)
levels(results2$trait)
levs2=c("Intelligence","EA","ASD","ADHD","SCZ","BIP")
results2$trait<-factor(results2$trait,levels=levs2)
levels(results2$trait)

## calculate minimum rhog at alpha=0.05 and beta=0.80, for each facet/condition
results_pwr<-subset(results2,pwr>=0.8)
min_rhog<-ddply(results_pwr,.(measure,trait,program),summarise,min_rg=min(rg,na.rm=TRUE))

# including gcta
power_plot_ai0<-ggplot(data = results2, aes(x = rg, y= pwr)) + 
  geom_hline(yintercept =0.8,color="black",linetype="dashed") + 
  geom_vline(data=min_rhog,aes(xintercept =min_rg),color="black",linetype="dashed") +
  geom_line(aes(color=program,group=program),size=1)  + 
  labs(x = bquote(''*rho*'(G)'), y = "", title = "") + 
  facet_grid(trait~measure,scales="free_x") + # coord_cartesian(xlim = c(0,0.20)) +
  theme_bw() +
  theme(axis.text=element_text(size=12,colour="black"),axis.title=element_text(size=14,colour="black")) +  
  theme( legend.title=element_text(size=12), legend.text=element_text(size=12),legend.position="bottom") +
  scale_color_manual(values=colrs)  +
  # labs(title=bquote(paste("Trait 1: N=",.(N1)," and ",h^2, "=",.(h21),"                                  Trait 2 (QT): ",h^2, "=",.(h22)) )) +
  NULL

power_plot_ai0

# without gcta
power_plot_ai<-ggplot(data = subset(results2,program!="GCTA"), aes(x = rg, y= pwr)) + 
  geom_hline(yintercept =0.8,color="black",linetype="dashed") + 
  geom_vline(data=subset(min_rhog,program!="GCTA"),aes(xintercept =min_rg),color="black",linetype="dashed") +
  geom_line(aes(color=program,group=program),size=1)  + 
  labs(x = bquote(''*rho*'(G)'), y = "", title = "") + 
  facet_grid(trait~measure,scales="free_x") + # coord_cartesian(xlim = c(0,0.20)) +
  theme_bw() +
  theme(axis.text=element_text(size=12,colour="black"),axis.title=element_text(size=14,colour="black")) +  
  theme( legend.title=element_text(size=12), legend.text=element_text(size=12),legend.position="bottom") +
  scale_color_manual(values=colrs)  +
  # labs(title=bquote(paste("Trait 1: N=",.(N1)," and ",h^2, "=",.(h21),"                                  Trait 2 (QT): ",h^2, "=",.(h22)) )) +
  NULL

power_plot_ai


ggsave(power_plot_ai,file=paste(out_dir,"gencor_power_GWASes_PT_LDSC_SumHer.png"),width=7,height=6)
#-----------------------------------------------
mytheme<-theme_bw() + theme(panel.spacing = unit(0, "lines"), 
                            strip.background = element_rect(fill="white"), strip.text = element_text(size=16), 
                            # axis.title.x=element_blank(), axis.ticks.x =element_blank(), # axis.text.x =element_blank(),
                            # axis.text.x = element_text(size=16,colour="black",hjust=1,vjust=.5),
                            # axis.title.y=element_text(size=16),axis.text.y=element_text(size=16,colour="black"),
                            title=element_text(size=16),
                            axis.title=element_text(size=16),axis.text=element_text(size=16,colour="black"),
                            legend.text=element_text(size=16), legend.title =element_text(size=16) ) 
mytheme2<-theme_bw() + theme(panel.spacing = unit(0, "lines"), 
                             strip.background = element_rect(fill="white"), strip.text = element_text(size=16), 
                             title=element_text(size=16),
                             axis.title=element_text(size=16,angle=0.90),axis.text=element_text(size=16,colour="black"),
                             legend.text=element_text(size=16), legend.title=element_blank(), legend.position="bottom") 


power_plot_ai2<-ggplot(data = subset(results2,program!="GCTA"), aes(x = rg, y= pwr)) + 
  geom_hline(yintercept =0.8,color="black",linetype="dashed") + 
  # geom_vline(data=subset(min_rhog,program!="GCTA"),aes(xintercept =min_rg),color="black",linetype="dashed") +
  geom_line(aes(color=measure,group=measure),size=1.2)  + 
  labs(x = bquote(''*rho*'(G)'), y = "", title = "") + 
  facet_grid(program~trait,scales="free_x") +
  mytheme2 + background_grid(major = "xy", minor = "none") + 
  scale_color_manual(values=colrs)  +
  # scale_colour_hue() +
  # scale_colour_brewer(palette="Set1")+
  scale_x_continuous(breaks=seq(0,0.20,0.05),labels=c("0","0.05","0.10","0.15","")) +
  coord_cartesian(xlim = c(0,0.20)) +
  NULL
power_plot_ai2
ggsave(power_plot_ai2,file=paste(out_dir,"gencor_power_GWASes_PT_LDSC_SumHer_poster.pdf"),width=14,height=6)


colrs=c('#214D9D','#AA1926','#EEA300')
power_plot_ai3<-ggplot(data = subset(results2,program!="GCTA"), aes(x = rg, y= pwr)) + 
  geom_hline(yintercept =0.8,color="black",linetype="dashed") + 
  # geom_vline(data=subset(min_rhog,program!="GCTA"),aes(xintercept =min_rg),color="black",linetype="dashed") +
  geom_line(aes(color=program,group=program),size=1)  + 
  labs(x = bquote(''*rho*'(G)'), y = "", title = "") + 
  facet_grid(measure~trait,scales="free_x") +
  mytheme2 + background_grid(major = "xy", minor = "none") + 
  scale_color_manual(values=colrs)  +
  # scale_colour_hue() +
  # scale_colour_brewer(palette="Set1")+
  scale_x_continuous(breaks=seq(0,0.20,0.05),labels=c("0","0.05","0.10","0.15","")) +
  coord_cartesian(xlim = c(0,0.20)) +
  NULL
power_plot_ai2
# ggsave(power_plot_ai2,file=paste(out_dir,"gencor_power_GWASes_PT_LDSC_SumHer_poster.pdf"),width=12,height=5)


# save.image(paste(out_dir,"GCTA_PowerCalculator_gencor_VOLUMES_MinMax_GWASpublic.RData",sep=""))
